#ifndef ERROR_CODE_H
#define ERROR_CODE_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
	ERROR_CODE_NONE = 0,

	/* System: -1 to -99 */
	ERROR_CODE_UNKNOWN = -1,
	ERROR_CODE_SYSTEM_HAL = -2,
	ERROR_CODE_SYSTEM_CLOCK = -3,

	/* AD4130: -100 to -199 */
	ERROR_CODE_AD4130_ILLEGAL_PARAM = -101,
	ERROR_CODE_AD4130_ILLEGAL_DEVICE_ID = -102,
	ERROR_CODE_AD4130_ILLEGAL_IOUT = -103,
	ERROR_CODE_AD4130_ILLEGAL_WRITE_LENGTH = -104,
	ERROR_CODE_AD4130_SPI = -105,
	ERROR_CODE_AD4130_SPI_BUSY = -106,
	ERROR_CODE_AD4130_SPI_TIMEOUT = -107,
	ERROR_CODE_AD4130_ID_MISMATCH = -108,

	/* AD4130 measurement: -200 to -299 */
	ERROR_CODE_MEASUREMENT_NOT_READY = -200,
	ERROR_CODE_MEASUREMENT_ILLEGAL_PARAM = -201,
	ERROR_CODE_MEASUREMENT_ILLEGAL_CHANNEL_ID = -202,
	ERROR_CODE_MEASUREMENT_ILLEGAL_IOUT = -203,
	ERROR_CODE_MEASUREMENT_STATUS = -204,
	ERROR_CODE_MEASUREMENT_STATUS_POR = -205,
	ERROR_CODE_MEASUREMENT_STATUS_AINP_OV_UV = -206,
	ERROR_CODE_MEASUREMENT_STATUS_AINM_OV_UV = -207,
	ERROR_CODE_MEASUREMENT_STATUS_REF_OV_UV = -208,
	ERROR_CODE_MEASUREMENT_STATUS_REF_DETECT = -209,
	ERROR_CODE_MEASUREMENT_STATUS_ADC = -210,
	ERROR_CODE_MEASUREMENT_STATUS_SPI_IGNORE = -211,
	ERROR_CODE_MEASUREMENT_STATUS_SPI_SCLK_COUNT = -212,
	ERROR_CODE_MEASUREMENT_STATUS_SPI_READ = -213,
	ERROR_CODE_MEASUREMENT_STATUS_SPI_WRITE = -214,
	ERROR_CODE_MEASUREMENT_STATUS_SPI_CRC = -215,
	ERROR_CODE_MEASUREMENT_STATUS_MM_CRC = -216,
	ERROR_CODE_MEASUREMENT_STATUS_ROM_CRC = -217,
	ERROR_CODE_MEASUREMENT_BELOW_RANGE = -218,
	ERROR_CODE_MEASUREMENT_ABOVE_RANGE = -219,

	/* Sensor fit: -300 to -399 */
	ERROR_CODE_SENSOR_FIT_ILLEGAL_PARAM = -301,
	ERROR_CODE_SENSOR_FIT_ILLEGAL_RESISTANCE = -302,
	ERROR_CODE_SENSOR_FIT_RANGE = -303,

	/* USB CDC: -400 to -499 */
	ERROR_CODE_USB_CDC_NOT_READY = 400,
	ERROR_CODE_USB_CDC_RECEIVING = -400,
	ERROR_CODE_USB_CDC_ILLEGAL_PARAM = -401,
	ERROR_CODE_USB_CDC_ILLEGAL_FORMAT = -402,
	ERROR_CODE_USB_CDC_ILLEGAL_LENGTH = -403,
	ERROR_CODE_USB_CDC_BUSY = -404,
	ERROR_CODE_USB_CDC_TRANSMIT = -405,

	/* USB CDC communication: -500 to -599 */
	ERROR_CODE_USB_COMM_NOT_READY = -500,
	ERROR_CODE_USB_COMM_ILLEGAL_PARAM = -501,
	ERROR_CODE_USB_COMM_ILLEGAL_COMMAND = -502,
	ERROR_CODE_USB_COMM_ILLEGAL_LENGTH = -503,
	ERROR_CODE_USB_COMM_TRANSMIT_BUSY = -504,

	/* USB CDC SCUP: -600 to -699 */
	ERROR_CODE_COEFFS_TRANSFER_NOT_READY = -600,
	ERROR_CODE_COEFFS_TRANSFER_ILLEGAL_PARAM = -601,
	ERROR_CODE_COEFFS_TRANSFER_ILLEGAL_FORMAT = -602,
	ERROR_CODE_COEFFS_TRANSFER_ILLEGAL_LENGTH = -603,

	/* Sensor coefficient: -700 to -799 */
	ERROR_CODE_COEFFS_STORAGE_NOT_FOUND = 700,
	ERROR_CODE_COEFFS_STORAGE_FULL = -700,
	ERROR_CODE_COEFFS_STORAGE_ILLEGAL_PARAM = -701,
	ERROR_CODE_COEFFS_STORAGE_ILLEGAL_LENGTH = -702,
	ERROR_CODE_COEFFS_STORAGE_ERASE = -703,
	ERROR_CODE_COEFFS_STORAGE_WRITE = -704,
	ERROR_CODE_COEFFS_STORAGE_VERIFY = -705,
	ERROR_CODE_COEFFS_DECODE_ILLEGAL_PARAM = -706,
	ERROR_CODE_COEFFS_DECODE_ILLEGAL_FORMAT = -707,
	ERROR_CODE_COEFFS_DECODE_ILLEGAL_VERSION = -708,
	ERROR_CODE_COEFFS_DECODE_CRC = -709,

	/* Modbus RTU: -1000 to -1099 */
	ERROR_CODE_MODBUS_RTU_REGISTER = -1001,
	ERROR_CODE_MODBUS_RTU_ILLEGAL_PARAM = -1002,
	ERROR_CODE_MODBUS_RTU_PORT = -1003,
	ERROR_CODE_MODBUS_RTU_RESOURCE = -1004,
	ERROR_CODE_MODBUS_RTU_IO = -1005,
	ERROR_CODE_MODBUS_RTU_STATE = -1006,
	ERROR_CODE_MODBUS_RTU_TIMEOUT = -1007
} ErrorCode_t;

#ifdef __cplusplus
}
#endif

#endif  /* ERROR_CODE_H */
