#ifndef SENSOR_COEFFS_FORMAT_H
#define SENSOR_COEFFS_FORMAT_H

#define SENSOR_COEFFS_FORMAT_VERSION				1U
#define SENSOR_COEFFS_FORMAT_HEADER_SIZE			8U
#define SENSOR_COEFFS_FORMAT_CRC_SIZE			4U
#define SENSOR_COEFFS_FORMAT_SEGMENT_HEADER_SIZE	20U
#define SENSOR_COEFFS_FORMAT_FLOAT_SIZE			4U

#define SENSOR_COEFFS_FORMAT_MAX_SEGMENTS	4U
#define SENSOR_COEFFS_FORMAT_MAX_ORDER		15U
#define SENSOR_COEFFS_FORMAT_COEFF_COUNT		(SENSOR_COEFFS_FORMAT_MAX_ORDER + 1U)

#define SENSOR_COEFFS_BINARY_MIN_SIZE	( \
		SENSOR_COEFFS_FORMAT_HEADER_SIZE \
		+ SENSOR_COEFFS_FORMAT_SEGMENT_HEADER_SIZE \
		+ SENSOR_COEFFS_FORMAT_FLOAT_SIZE \
		+ SENSOR_COEFFS_FORMAT_CRC_SIZE \
)

#define SENSOR_COEFFS_BINARY_MAX_SIZE	( \
		SENSOR_COEFFS_FORMAT_HEADER_SIZE \
		+ SENSOR_COEFFS_FORMAT_MAX_SEGMENTS \
		* ( \
				SENSOR_COEFFS_FORMAT_SEGMENT_HEADER_SIZE \
				+ SENSOR_COEFFS_FORMAT_COEFF_COUNT \
				* SENSOR_COEFFS_FORMAT_FLOAT_SIZE \
		) \
		+ SENSOR_COEFFS_FORMAT_CRC_SIZE \
)

#endif  /* SENSOR_COEFFS_FORMAT_H */
